name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.7
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.2
  dcli: ^3.0.2
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: 8511f17a0dfa721e8f0ec2e0b0aae409f509e102
  znn_ledger_dart:
    git:
      url: https://github.com/zenon-network/znn_ledger_dart.git
      ref: main
  bip39: ^1.0.6
  convert: ^3.1.1
  collection: ^1.18.0
      
dev_dependencies:
  test: ^1.24.4
  lints: ^2.1.1
